<?php ob_start() ?>
<script type="text/javascript">
WebFontConfig = {
google: { families: [ '<?= (isset($fontFamily)?$fontFamily:'Pacifico:200,800:latin')?>' ] }
};
var cb = function() {
    var wf = document.createElement('script');
    wf.src = '//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
};
 
// shim layer with setTimeout fallback. Thanks Paul Irish http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/
window.requestAnimFrame = (function(){
 return  window.requestAnimationFrame       
        || window.webkitRequestAnimationFrame 
        || window.mozRequestAnimationFrame    
        || function( callback ){
            window.setTimeout(callback, 1000 / 60);
        };
})();
                                      
//Remove the old raf var and set it with our SHIM instead.
//var raf = requestAnimationFrame || mozRequestAnimationFrame || webkitRequestAnimationFrame || msRequestAnimationFrame;
var raf = requestAnimFrame;
 
if(raf){
  raf(cb);
}else{
  window.addEventListener('load', cb);
}
</script>
<?php $this->scriptalicious()->addInline('google_webfont', ob_get_clean()) ?>
